### ISSUE TITLE
You can't choose file with .GIF extension instead of .gif for custom logo

### ISSUE THREAD

**Issue by sdryapko** [epam/ai-dial-chat#1105]
### EPAM AI DIAL chat version

0.8.0

### What happened?

You can't choose file with .GIF extension instead of .gif for custom logo

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The fix was verified on staging environment successfully. Now extension is changed to lower case, so if to select file.GIF, it is updated and uploaded to DIAL as file.gif. 
Note: user has to delete and re-upload all the files, where extension is in capital letters as DIAL still doesn't work with such files.
