### ISSUE TITLE
Need to check assistant model id only for "assistant" type

### ISSUE THREAD

**Issue by Alexander-Kezik** [epam/ai-dial-chat#1179]
### EPAM AI DIAL chat version

0.8

### What happened?

![image](https://github.com/epam/ai-dial-chat/assets/98586297/fe13c18a-581c-4b0d-9a5f-d7b70c22713c)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The issue was reproduced and verified on local dev machines. Though I was not able to reproduce the issue on staging server (due to specific steps), it was verified that no regression issues was found. On staging server it was verified that "Not allowed models" message appears in correct way for the chat with not-existed model and in assistant with not existed model; conversation can be continued if to change chat settings to existed model.
