### ISSUE TITLE
[Publication]: Published prompts folders are displayed in Pinned section when Export/Import all prompts

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#1693]
### EPAM AI DIAL chat version

0.14.0

### How to reproduce

Precondition:
there are some folders and prompts in Organization section
there is at least one prompt created by user

Steps:
1. User Export all prompts
2. User import the file from p1
3. user refresh page

### Actual result

2. the whole structure from Organization are displayed in Pinned section -  bug

3. prompt folders from Organizations are not displayed in pinned section

### Expected result

Published pormpts/ chats should not be exported while Export all

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
The issue is also reproduced on the 'Conversations list' panel. Steps: export the whole structure when organization exists -> Select some folders and chats and Delete selected ones -> import the whole structure
![image](https://github.com/epam/ai-dial-chat/assets/111180458/85abb2ff-7933-40bd-ad5c-803ee84e2bd3)

**Comment by YauheniyaH** [comment]
Verified on staging - fixed
