### ISSUE TITLE
[Custom app]: error message appear if delete app from new conversation

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-chat#2021]
### EPAM AI DIAL chat version

0.17.0

### How to reproduce

Precondition:
user created custom application, application was NOT published 

Steps:
1. Click New conversation button
2. On central part click 'See full list'
3. Select created but not published application
4. use context menu of the app and delete app

### Actual result

error message is displayed
![Screenshot 2024-09-02 at 17 21 08](https://github.com/user-attachments/assets/7d425258-b75b-43c6-90c3-17ed7398573d)
Application was deleted

### Expected result

Application should be deleted without any error messages
Nearest model (or assistant, or app) from recent should be selected for this chat

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
Return the ticket to developer as due to some other cases to be consistent we need to change the expected result:

1.  Now there is no unnecessary error message -> ok
2. If to delete from the custom app from the current "New conversation", the first model from recent is set -> **bug due to changed expected result** We need to set the default icon and selected 'Not allowed model'
[Volha Oct. 11th ] agreed with YH to leave as is: the initial expected result. If the conversation is focused, user deleted custom app => the next app from talk to is assigned.
3. Be sure to do the same for other New conversations, which are not focused. Expected: default icon and selected only "Not allowed model". Now it should be fixed and it looks in the following way:
![image](https://github.com/user-attachments/assets/0ef83f43-ca33-43d2-b3de-816a7bb8baf1)

4. Icons for the conversation with history appears after browser refresh -> **bug** Icon should be reset to default immediately.
5. For the conversation with history no need to select recent model -> **bug** 
![image](https://github.com/user-attachments/assets/7a151576-23b7-4fd1-bd14-b65af15866cc)


https://github.com/user-attachments/assets/11db130d-b570-4622-8df0-9b7f6a60c09f

**Comment by VolhaBazhkova** [comment]
Verified on staging env successfully
