### ISSUE TITLE
reduce session token size

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-chat#2028]
### EPAM AI DIAL chat version

0.16.4

### What happened?

reduce session token size

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by VolhaBazhkova** [comment]
In 0.16 version session token size was made bigger, but DIAL failed to login for some users because of big amount of groups in token claims. We applied the fix as patch to 0.16 version to fix this and received the confirmation from user that the fix helped.
Verified that in 0.15 (sales) and in 0.17 (staging) we have equal token size (tested in incognito mode Network - session - set-cookie)
