### ISSUE TITLE
[Custom application] Add padding to topics input

### ISSUE THREAD

**Issue by DaryaKarniyenka** [epam/ai-dial-chat#2295]
### EPAM AI DIAL chat version

0.18.0

### How to reproduce

Open "Add app" window and add a lot of topics

### Actual result

![image](https://github.com/user-attachments/assets/32a1433f-90c0-4b99-a760-c74182276826)

### Expected result

Add 4px padding between lines. Pin right icon buttons to the top. Divider should be short.

![image](https://github.com/user-attachments/assets/74703d4a-b4cf-4b2b-a08d-c0b3e57e4228)

### Confidential information

- [X] I confirm that do not share any confidential information

**Comment by YauheniyaH** [comment]
1. Padding on the bottom should be equal to padding on the top. Now they are different
![Image](https://github.com/user-attachments/assets/dd8fbe81-4c32-4bfb-bac4-572f107f2227)

2. tag's height should be 30px ( according to design) instead of 26px
3.  ![Image](https://github.com/user-attachments/assets/29552060-aff7-4ed3-883a-19c532c7687f)

**Comment by YauheniyaH** [comment]
verified on staging successfully
