### ISSUE TITLE
Support rendering of images in attachments specified via URL

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-chat#267]
# Actual behaviour

An application returns an image in attachment like this:

```json
{
  "index": 0,
  "type": "image/png",
  "title": "image",
  "url": "/Keys/EPM-RTC-test/files/stability/f0e6aac4670bdcc30d35cf6637ad25d3543c916ee8f3249006b1a6c54d73879e.png"
}
```

The chat doesn't render the image - it only allows to download it. 

It hurts UX: to much moves for a user to make to see an image generated by an application.

# Expected behaviour

The chat must render the image in the same way it already does when an image is encoded in base64 data. 

# How to reproduce

Attach an image to a message for `Echo` application. It will reply with the same attachment.

# Notes

The issue blocks https://github.com/epam/ai-dial-adapter-bedrock/issues/29

**Comment by VolhaBazhkova** [comment]
Verified on staging server. Now pictures can be expanded and collapsed which makes UX user-friendly if the picture is uploaded from device. If the picture is uploaded from application, there is an issue, which is being fixed in https://github.com/epam/ai-dial-core/issues/69- by core team.
Please note that there is no Download button for the attachment-pictures, see reported enhancement #124
