### ISSUE TITLE
Icon is not changed in chat header when new icon set

### ISSUE THREAD

**Issue by mikitabut** [epam/ai-dial-chat#545]
![image](https://github.com/epam/ai-dial-chat/assets/6322751/8bb2771c-026e-414a-91f8-bab17265254a)

**Comment by VolhaBazhkova** [comment]
Verified successfully using the following steps:
1. Overlay on site1 based on model1 and send any message there
2. While response is being generated, in the same browser but in new tab open Overlay on site2 based on model2
3. Check that Overlay1 has model1 in chat header and on hover over the model1 icon
4. Check that Overlay2 has model2 in chat header and on hover over the model2 icon (this was fixed)


We still have an issue that Overlay2 has response with icon from Overlay1. As the fix is time-consuming and requires significant code changes, the fix of the issue is delayed.
