### ISSUE TITLE
Conversation setting screen shown if connection lost

### ISSUE THREAD

**Issue by irinakartun** [epam/ai-dial-chat#790]
**Steps:**
1 Create New conversation
2 Set Offline mode in network console
3 Send any request

**Actual result:** error is shown as a response and then conversation setting shown

**Expected result:** error is shown as a response, chat with error response is shown for user, Regenerate btn is available

https://github.com/epam/ai-dial-chat/assets/15156585/afe17835-abe6-437c-9996-087200e6dfeb

**Comment by IlyaBondar** [comment]
suggestion: try to stay input with text if we can't send message

**Comment by VolhaBazhkova** [comment]
It was verified on staging environment. Now the behaviour is the following
1. Create New conversation
2. Set Offline mode in network console
3. Send any prompt -> Red error appears -> DIAL is lost because of no internet connection
4. Turn internet connection on -> the conversation doesn't have saved sent message, no red error saved
