### ISSUE TITLE
Implement attachment functionality

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-chat#80]
See https://github.com/epam/ai-dial-core/issues/29

We should have availability to add attachments to user message

The attachment should be loaded before sending. Attachment size should be up to 1 gb.

When clicking on icon modal will be opened with all attached files before and with folder structure.

Open Questions:

1. Do we need to have any UI where we select already existing attachments? - YES
2. Should we be able to select multiple attachments? - YES
3. What type of attachments should be supported? - Backend will provide type of attachments supported by model
4. Should we be able to see already loaded attachments and manage them? - YES

Design will be provided (in progress)

**Comment by mikitabut** [comment]
Currently next things have been implemented:

1. For some applications we can get from listing next params `input_attachment_types` and `max_input_attachments` (For more details see https://github.com/epam/ai-dial-core/issues/34) which saying us do we need to show attach button or not
2. Also we put this attachment button under feature flag
3. When clicking on attach button user will see 2 options: 'Attach uploaded files' and 'Upload from device'
4. When clicking on 'Attach uploaded files' user will see file select modal will be able to manage already uploaded files, create folders and upload more files from there(to upload files user will see same steps as in point 5, except that after clicking attach button user will be navigated back to file select modal). 
5. When clicking on 'Upload from device' the user will be able to select files from device and put them to existing folders(or create new folders). After clicking on attach button the modal will be closed and he will see progress of file uploading

What haven't been done or done differently:

1. UI doesn't have manage files modal which opened from left side bar (Scope https://github.com/epam/ai-dial-chat/issues/211)
2. [TODO] UI doestn't allow to rename files, move files, rename folders, move folder, remove folder(remove folder doing automatically after removing all files from it and reloading the page).
3. From UI it's not possible to upload file to folder directly (Scope https://github.com/epam/ai-dial-chat/issues/211)
4. Some actions like download file, add new folder, delete file are under context menu
5. [TODO] Currently UI not supporting bulk updates for folders and files like download or delete
6. UI don't show recent updates section
7. UI don't show loader when listing for files and folders from root folders are loading (Scope https://github.com/epam/ai-dial-chat/issues/211)
8. It's not possible to edit already attached files in user message (Scope https://github.com/epam/ai-dial-chat/issues/211)

Some known issues and notes:
1. When cancelling upload folder it's not cancelling for fetch request, just on UI
2. When searching for folders and files - folders not filtered, because the list of folders is not fetched one time but fetching when you opening them
